apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress-production
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-failed.discord: "true"
    notifications.argoproj.io/subscribe.on-sync-succeeded.discord: "true"
    notifications.argoproj.io/subscribe.on-health-degraded.discord: "true"
spec:
  project: default
  source:
    repoURL: https://github.com/2Qic1/wordpress-ci-cd
    targetRevision: HEAD
    path: deployment
  destination:
    server: https://kubernetes.default.svc
    namespace: wordpress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true
    - Validate=true
