apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-load-test
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cpu-load-test
  template:
    metadata:
      labels:
        app: cpu-load-test
    spec:
      containers:
      - name: stress
        image: progrium/stress
        command: ["stress"]
        args: ["--cpu", "4", "--timeout", "1800s"]
        resources:
          limits:
            cpu: "1000m"
            memory: "256Mi"
          requests:
            cpu: "800m"
            memory: "128Mi"
