apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: wordpress
type: Opaque
data:
  root-password: cm9vdHBhc3N3b3JkMTIz # rootpassword123
  database: d29yZHByZXNz # wordpress
  username: d29yZHByZXNz # wordpress
  password: d29yZHByZXNzcGFzc3dvcmQxMjM= # wordpresspassword123
