apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secrets
  namespace: wordpress
type: Opaque
data:
  mysql-root-password: cGFzc3dvcmQ=  # password
  mysql-password: d29yZHByZXNz  # wordpress
  mysql-database: d29yZHByZXNz  # wordpress
  mysql-user: d29yZHByZXNz  # wordpress
